# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTwittertest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_twittertest(self):
    # Test name: twittertest
    # Step # | name | target | value
    # 1 | open | /i/flow/login | 
    self.driver.get("https://twitter.com/i/flow/login")
    # 2 | setWindowSize | 727x782 | 
    self.driver.set_window_size(727, 782)
    # 3 | click | name=text | 
    self.driver.find_element(By.NAME, "text").click()
    # 4 | type | name=text | migueleras
    self.driver.find_element(By.NAME, "text").send_keys("migueleras")
    # 5 | sendKeys | name=text | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "text").send_keys(Keys.ENTER)
    # 6 | type | name=password | miguel151990
    self.driver.find_element(By.NAME, "password").send_keys("miguel151990")
    # 7 | sendKeys | name=password | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
  
