import os
import pandas as pd

regla1 = '073_redmi.xls'
regla2 = '73_server.xls'



df1 = pd.read_excel(regla1)
df2 = pd.read_excel(regla2)

print(df1)

values1 = df1[['INFORMACION','SUBSISTEMA_ORIGEN','TRANSACCION_ORIGEN','DEBITO_CREDITO','GRUPO_PRODUCTO_CUENTA_VISTA_01=CORRIENTES, 02=AHORROS','PRODUCTO','COMANDO','CATEGORIA','SUBSISTEMA_A_EJECUTAR','TRANSACCION_A_EJECUTAR','TRANSACCION_S32','RAZON_S32','RAZON_S32_REVERSO','CONCEPTO_S32','TIPO','GRUPO','CAJA_NORMAL','CAJA_DIFERIDA']]
values2 = df2[['INFORMACION','SUBSISTEMA_ORIGEN','TRANSACCION_ORIGEN','DEBITO_CREDITO','GRUPO_PRODUCTO_CUENTA_VISTA_01=CORRIENTES, 02=AHORROS','PRODUCTO','COMANDO','CATEGORIA','SUBSISTEMA_A_EJECUTAR','TRANSACCION_A_EJECUTAR','TRANSACCION_S32','RAZON_S32','RAZON_S32_REVERSO','CONCEPTO_S32','TIPO','GRUPO','CAJA_NORMAL','CAJA_DIFERIDA']]


dataframes = [values1, values2]

join = pd.concat(dataframes)

join.to_excel('73.xls')





